# Generated by Django 5.1.6 on 2025-03-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('topic', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('qos', models.IntegerField()),
                ('retain', models.BooleanField()),
                ('publisher_id', models.CharField(default='unknown', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, default=None, null=True)),
            ],
        ),
    ]
