# Generated by Django 5.1.6 on 2025-02-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiemApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='qos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='retain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='topic',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
