# Generated by Django 5.1.6 on 2025-02-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiemApp', '0002_log_qos_log_retain_log_topic_alter_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='publisher_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
