# Generated by Django 5.1.6 on 2025-03-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiemApp', '0002_device_rule_alter_log_timestamp_log_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='pattern',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
