# Generated by Django 5.1.6 on 2025-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiemApp', '0003_log_publisher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='unknown', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='qos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='retain',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
