--
-- PostgreSQL database dump
--

-- Dumped from database version 15.7
-- Dumped by pg_dump version 15.7

-- Started on 2025-04-10 09:58:02 IST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16384)
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- TOC entry 3751 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 234 (class 1259 OID 25054)
-- Name: Linkedin_feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Linkedin_feedback" (
    id bigint NOT NULL,
    feedback_type character varying(50) NOT NULL,
    feedback_text jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    updated_by_id integer NOT NULL,
    user_id integer NOT NULL,
    survey_id bigint NOT NULL
);


ALTER TABLE public."Linkedin_feedback" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 25053)
-- Name: Linkedin_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Linkedin_feedback" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Linkedin_feedback_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 25062)
-- Name: Linkedin_feedbackscore; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Linkedin_feedbackscore" (
    id bigint NOT NULL,
    score integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    feedback_id bigint NOT NULL,
    updated_by_id integer NOT NULL
);


ALTER TABLE public."Linkedin_feedbackscore" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 25061)
-- Name: Linkedin_feedbackscore_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Linkedin_feedbackscore" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Linkedin_feedbackscore_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 25048)
-- Name: Linkedin_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Linkedin_question" (
    id bigint NOT NULL,
    question_text character varying(255) NOT NULL
);


ALTER TABLE public."Linkedin_question" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 25047)
-- Name: Linkedin_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Linkedin_question" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Linkedin_question_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 25068)
-- Name: Linkedin_survey; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Linkedin_survey" (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    updated_by_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public."Linkedin_survey" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 25067)
-- Name: Linkedin_survey_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Linkedin_survey" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Linkedin_survey_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 25079)
-- Name: Linkedin_surveyanswer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Linkedin_surveyanswer" (
    id bigint NOT NULL,
    answer_text character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    question_id bigint NOT NULL,
    survey_id bigint NOT NULL,
    updated_by_id integer NOT NULL
);


ALTER TABLE public."Linkedin_surveyanswer" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 25078)
-- Name: Linkedin_surveyanswer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Linkedin_surveyanswer" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Linkedin_surveyanswer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24962)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24961)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24970)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24969)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 24956)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24955)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 24976)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24984)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24983)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 24975)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 24990)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 24989)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 25164)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 25163)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24948)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24947)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 24940)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 24939)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 25192)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 3553 (class 2606 OID 25060)
-- Name: Linkedin_feedback Linkedin_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedback"
    ADD CONSTRAINT "Linkedin_feedback_pkey" PRIMARY KEY (id);


--
-- TOC entry 3560 (class 2606 OID 25066)
-- Name: Linkedin_feedbackscore Linkedin_feedbackscore_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedbackscore"
    ADD CONSTRAINT "Linkedin_feedbackscore_pkey" PRIMARY KEY (id);


--
-- TOC entry 3550 (class 2606 OID 25052)
-- Name: Linkedin_question Linkedin_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_question"
    ADD CONSTRAINT "Linkedin_question_pkey" PRIMARY KEY (id);


--
-- TOC entry 3564 (class 2606 OID 25072)
-- Name: Linkedin_survey Linkedin_survey_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_survey"
    ADD CONSTRAINT "Linkedin_survey_pkey" PRIMARY KEY (id);


--
-- TOC entry 3569 (class 2606 OID 25083)
-- Name: Linkedin_surveyanswer Linkedin_surveyanswer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_surveyanswer"
    ADD CONSTRAINT "Linkedin_surveyanswer_pkey" PRIMARY KEY (id);


--
-- TOC entry 3523 (class 2606 OID 25190)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3528 (class 2606 OID 25005)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3531 (class 2606 OID 24974)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3525 (class 2606 OID 24966)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3518 (class 2606 OID 24996)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3520 (class 2606 OID 24960)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3539 (class 2606 OID 24988)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3542 (class 2606 OID 25020)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 3533 (class 2606 OID 24980)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3545 (class 2606 OID 24994)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3548 (class 2606 OID 25034)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 3536 (class 2606 OID 25185)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 3575 (class 2606 OID 25171)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3513 (class 2606 OID 24954)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3515 (class 2606 OID 24952)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3511 (class 2606 OID 24946)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3579 (class 2606 OID 25198)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3551 (class 1259 OID 25099)
-- Name: Linkedin_feedback_created_by_id_7311d833; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_feedback_created_by_id_7311d833" ON public."Linkedin_feedback" USING btree (created_by_id);


--
-- TOC entry 3554 (class 1259 OID 25138)
-- Name: Linkedin_feedback_survey_id_4845386a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_feedback_survey_id_4845386a" ON public."Linkedin_feedback" USING btree (survey_id);


--
-- TOC entry 3555 (class 1259 OID 25100)
-- Name: Linkedin_feedback_updated_by_id_08b2af86; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_feedback_updated_by_id_08b2af86" ON public."Linkedin_feedback" USING btree (updated_by_id);


--
-- TOC entry 3556 (class 1259 OID 25101)
-- Name: Linkedin_feedback_user_id_8396214d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_feedback_user_id_8396214d" ON public."Linkedin_feedback" USING btree (user_id);


--
-- TOC entry 3557 (class 1259 OID 25117)
-- Name: Linkedin_feedbackscore_created_by_id_6072878a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_feedbackscore_created_by_id_6072878a" ON public."Linkedin_feedbackscore" USING btree (created_by_id);


--
-- TOC entry 3558 (class 1259 OID 25118)
-- Name: Linkedin_feedbackscore_feedback_id_1b9fbdd9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_feedbackscore_feedback_id_1b9fbdd9" ON public."Linkedin_feedbackscore" USING btree (feedback_id);


--
-- TOC entry 3561 (class 1259 OID 25119)
-- Name: Linkedin_feedbackscore_updated_by_id_02378e71; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_feedbackscore_updated_by_id_02378e71" ON public."Linkedin_feedbackscore" USING btree (updated_by_id);


--
-- TOC entry 3562 (class 1259 OID 25135)
-- Name: Linkedin_survey_created_by_id_7fab5eff; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_survey_created_by_id_7fab5eff" ON public."Linkedin_survey" USING btree (created_by_id);


--
-- TOC entry 3565 (class 1259 OID 25136)
-- Name: Linkedin_survey_updated_by_id_3246b156; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_survey_updated_by_id_3246b156" ON public."Linkedin_survey" USING btree (updated_by_id);


--
-- TOC entry 3566 (class 1259 OID 25137)
-- Name: Linkedin_survey_user_id_8f957d6f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_survey_user_id_8f957d6f" ON public."Linkedin_survey" USING btree (user_id);


--
-- TOC entry 3567 (class 1259 OID 25159)
-- Name: Linkedin_surveyanswer_created_by_id_5d861a0d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_surveyanswer_created_by_id_5d861a0d" ON public."Linkedin_surveyanswer" USING btree (created_by_id);


--
-- TOC entry 3570 (class 1259 OID 25160)
-- Name: Linkedin_surveyanswer_question_id_55e6d3c5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_surveyanswer_question_id_55e6d3c5" ON public."Linkedin_surveyanswer" USING btree (question_id);


--
-- TOC entry 3571 (class 1259 OID 25161)
-- Name: Linkedin_surveyanswer_survey_id_7ad9f4d9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_surveyanswer_survey_id_7ad9f4d9" ON public."Linkedin_surveyanswer" USING btree (survey_id);


--
-- TOC entry 3572 (class 1259 OID 25162)
-- Name: Linkedin_surveyanswer_updated_by_id_118d28d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Linkedin_surveyanswer_updated_by_id_118d28d7" ON public."Linkedin_surveyanswer" USING btree (updated_by_id);


--
-- TOC entry 3521 (class 1259 OID 25191)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3526 (class 1259 OID 25016)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3529 (class 1259 OID 25017)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3516 (class 1259 OID 25002)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 3537 (class 1259 OID 25032)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 3540 (class 1259 OID 25031)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 3543 (class 1259 OID 25046)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 3546 (class 1259 OID 25045)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 3534 (class 1259 OID 25186)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 3573 (class 1259 OID 25182)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3576 (class 1259 OID 25183)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 3577 (class 1259 OID 25200)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 3580 (class 1259 OID 25199)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3588 (class 2606 OID 25084)
-- Name: Linkedin_feedback Linkedin_feedback_created_by_id_7311d833_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedback"
    ADD CONSTRAINT "Linkedin_feedback_created_by_id_7311d833_fk_auth_user_id" FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3589 (class 2606 OID 25073)
-- Name: Linkedin_feedback Linkedin_feedback_survey_id_4845386a_fk_Linkedin_survey_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedback"
    ADD CONSTRAINT "Linkedin_feedback_survey_id_4845386a_fk_Linkedin_survey_id" FOREIGN KEY (survey_id) REFERENCES public."Linkedin_survey"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3590 (class 2606 OID 25089)
-- Name: Linkedin_feedback Linkedin_feedback_updated_by_id_08b2af86_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedback"
    ADD CONSTRAINT "Linkedin_feedback_updated_by_id_08b2af86_fk_auth_user_id" FOREIGN KEY (updated_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3591 (class 2606 OID 25094)
-- Name: Linkedin_feedback Linkedin_feedback_user_id_8396214d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedback"
    ADD CONSTRAINT "Linkedin_feedback_user_id_8396214d_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3592 (class 2606 OID 25107)
-- Name: Linkedin_feedbackscore Linkedin_feedbacksco_feedback_id_1b9fbdd9_fk_Linkedin_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedbackscore"
    ADD CONSTRAINT "Linkedin_feedbacksco_feedback_id_1b9fbdd9_fk_Linkedin_" FOREIGN KEY (feedback_id) REFERENCES public."Linkedin_feedback"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3593 (class 2606 OID 25102)
-- Name: Linkedin_feedbackscore Linkedin_feedbackscore_created_by_id_6072878a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedbackscore"
    ADD CONSTRAINT "Linkedin_feedbackscore_created_by_id_6072878a_fk_auth_user_id" FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3594 (class 2606 OID 25112)
-- Name: Linkedin_feedbackscore Linkedin_feedbackscore_updated_by_id_02378e71_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_feedbackscore"
    ADD CONSTRAINT "Linkedin_feedbackscore_updated_by_id_02378e71_fk_auth_user_id" FOREIGN KEY (updated_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3595 (class 2606 OID 25120)
-- Name: Linkedin_survey Linkedin_survey_created_by_id_7fab5eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_survey"
    ADD CONSTRAINT "Linkedin_survey_created_by_id_7fab5eff_fk_auth_user_id" FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3596 (class 2606 OID 25125)
-- Name: Linkedin_survey Linkedin_survey_updated_by_id_3246b156_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_survey"
    ADD CONSTRAINT "Linkedin_survey_updated_by_id_3246b156_fk_auth_user_id" FOREIGN KEY (updated_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3597 (class 2606 OID 25130)
-- Name: Linkedin_survey Linkedin_survey_user_id_8f957d6f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_survey"
    ADD CONSTRAINT "Linkedin_survey_user_id_8f957d6f_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3598 (class 2606 OID 25144)
-- Name: Linkedin_surveyanswer Linkedin_surveyanswe_question_id_55e6d3c5_fk_Linkedin_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_surveyanswer"
    ADD CONSTRAINT "Linkedin_surveyanswe_question_id_55e6d3c5_fk_Linkedin_" FOREIGN KEY (question_id) REFERENCES public."Linkedin_question"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3599 (class 2606 OID 25139)
-- Name: Linkedin_surveyanswer Linkedin_surveyanswer_created_by_id_5d861a0d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_surveyanswer"
    ADD CONSTRAINT "Linkedin_surveyanswer_created_by_id_5d861a0d_fk_auth_user_id" FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3600 (class 2606 OID 25149)
-- Name: Linkedin_surveyanswer Linkedin_surveyanswer_survey_id_7ad9f4d9_fk_Linkedin_survey_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_surveyanswer"
    ADD CONSTRAINT "Linkedin_surveyanswer_survey_id_7ad9f4d9_fk_Linkedin_survey_id" FOREIGN KEY (survey_id) REFERENCES public."Linkedin_survey"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3601 (class 2606 OID 25154)
-- Name: Linkedin_surveyanswer Linkedin_surveyanswer_updated_by_id_118d28d7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Linkedin_surveyanswer"
    ADD CONSTRAINT "Linkedin_surveyanswer_updated_by_id_118d28d7_fk_auth_user_id" FOREIGN KEY (updated_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3582 (class 2606 OID 25011)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3583 (class 2606 OID 25006)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3581 (class 2606 OID 24997)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3584 (class 2606 OID 25026)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3585 (class 2606 OID 25021)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3586 (class 2606 OID 25040)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3587 (class 2606 OID 25035)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3602 (class 2606 OID 25172)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3603 (class 2606 OID 25177)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-04-10 09:58:02 IST

--
-- PostgreSQL database dump complete
--

